### ISSUE TITLE
Stop annoying json deserialization errors

### ISSUE THREAD

**Issue by sc68cal** [sc68cal/Kostyor#30]
Basically, we need to stop this copy & paste pattern in our unit tests of JSON decoding responses from the server.

    Traceback (most recent call last):
      File "/Users/scollins/src/Kostyor/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "kostyor/tests/unit/rest_api/test.py", line 126, in test_create_cluster_upgrade
        received = json.loads(data)
      File "/Users/scollins/.pyenv/versions/2.7.11/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/Users/scollins/.pyenv/versions/2.7.11/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/scollins/.pyenv/versions/2.7.11/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

**Comment by sc68cal** [comment]
@jvarlamova basically this error happens when something inside the `rest_api.py` process throws an uncaught exception

**Comment by sc68cal** [comment]
Basically we need to check if `data` is not `Null` before we do a json.loads - and we do it enough where maybe we should think about the DRY principle and cut down on the amount of copy & paste

**Comment by ikalnitsky** [comment]
Fixed by https://github.com/sc68cal/Kostyor/pull/49
